apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: failure-db-connector
  namespace: fapi
spec:
  action: pod-failure
  mode: all
  selector:
    namespaces:
      - fapi
    labelSelectors:
        app: db-connector
  duration: "2m"