apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-mysql
  namespace: fapi
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - fapi
    labelSelectors:
      app: mysql